name: CI/CD Cerebro V2X

# Only activetes when a push in main branch is done
on:
  push:
    branches:
      - main

jobs:
  # 1: Q&A
  build-and-test:
    runs-on: ubuntu-latest # GitHub proived ubuntu machine
    
    steps:
      - name: 1. Descargar nuestro código al ordenador de GitHub
        uses: actions/checkout@v4

      - name: 2. Instalar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # match with azure version

      - name: 3. Instalar dependencias (Librerías, Bandit y Pytest)
        # install requirements.txt and testing tools
        run: pip install -r src/cloud/twin-core-processor/requirements.txt pytest bandit

      - name: 4. SAST - (Static Application Security Testing) with bandit linter
        run: bandit -r ./src 

      - name: 5. Ejecutar Tests
        run: pytest tests/

  # 2: Azure transport
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-test # Wait until built-and-test finish with success
    
    steps:
      - name: 1. Descargar nuestro código de nuevo
        uses: actions/checkout@v4

      - name: 2. Empaquetar y Desplegar en Azure
        uses: Azure/functions-action@v1
        with:
          app-name: 'brain-v2x-madrid' # Azure APP axact name
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}