# CI/CD DevSecOps Pipeline using OIDC Authentication
name: Build and deploy Python project to Azure Function App - brain-v2x-madrid

# Only activates when a push to the main branch is done
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Keep the deployment path at root, because we will compress ONLY the target folder later
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  # Match with Azure runtime version (3.11), even if local native Fedora uses 3.14
  PYTHON_VERSION: '3.11' 

jobs:
  # 1: Q&A (Quality and Assurance)
  build-and-test:
    runs-on: ubuntu-latest # GitHub provides an ubuntu machine
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        # Install requirements.txt and testing tools
        run: pip install -r src/cloud/twin-core-processor/requirements.txt pytest bandit

      - name: SAST - Static Application Security Testing (Bandit)
        run: bandit -ll -r ./src 

      - name: Run Pytest
        run: pytest tests/

      - name: Zip artifact for deployment
        # Enter the exact folder and compress only the backend to send it clean to Azure
        run: |
          cd src/cloud/twin-core-processor
          zip -r ../../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  # 2: Azure transport
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-test # Wait until build-and-test finishes with success
    permissions:
      id-token: write # CRUCIAL FOR OIDC! (Zero Trust)
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8FFF811778FD418F903C76C41B5D4091 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F339424526CB4BF497CB2A0A0F4C6854 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7FC6533AB0D64262BE68F0A2374B4A79 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'brain-v2x-madrid'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}